### ISSUE TITLE
Thunderbird version 78.2.2 add-on is not compatible 

### ISSUE THREAD

**Issue by rlonghitano** [RealRaven2000/FiltaQuilla#72] opened 2020-09-18 15:58 UTC
No longer works with Thunderbird.  Use it to auto print incoming emails, stopped working yesterday.  Deleted currant filter and added a new filter but the print command is not listed

**Comment by RealRaven2000** [comment] 2020-09-18 17:37
this is a duplicate of issue #64 leave a comment there to be notified of when we start conversion / beta versions,

**Closed by RealRaven2000** 2020-09-18 17:37 UTC
