### ISSUE TITLE
Problem with UNC path Save Attachments To

### ISSUE THREAD

**Issue by skoczek-koczy** [RealRaven2000/FiltaQuilla#122] opened 2021-09-07 10:59 UTC
Hello, 
I have some isue with one option of this wonderwful addons :)
I use this addon for saving attachment files on a local server. Everything works fine, files are saved in the given location but when i restart the computer the save path of the files changes :/ The addos cuts off one slash. 

for example oryginal path is \\\serwer\example but when im restert the program is changes on \serwer\example

In consequently the files are not saved.  

If you have solution for this problem pleas share them :)

**Comment by RealRaven2000** [comment] 2021-09-07 16:04
> for example oryginal path is \\serwer\example but when im restert the program is changes on \serwer\example
> 
> In consequently the files are not saved.
> 
> If you have solution for this problem pleas share them :)

It's a problem with the way Thunderbird stores filters - the best workaround is permanently mapping a network drive letter to the root folder and then using this.

**Comment by RealRaven2000** [comment] 2024-02-21 12:58
Closing as duplicate of #79 - please follow that one for updates.

**Closed as completed by RealRaven2000** 2024-02-21 12:58 UTC
Labels: attachments
