### ISSUE TITLE
Folder Name Condition issue

### ISSUE THREAD

**Issue by El-Pazzo** [RealRaven2000/FiltaQuilla#10] opened 2019-03-29 16:09 UTC
Hi,
at least for German, Folder name (Verzeichnisname) does not work anymore. Within an existing filter the line with that filter is greyed out. If you try to add it via dropdown, Verzeichnisname does not show up as an option.

regards,
Pascal

**Comment by RealRaven2000** [comment] 2019-03-29 17:26
Please check your FiltaQuilla options - is the option selected in "Suchbegriffe"?

I was able to define it from here.
![Filter bearbeiten](https://user-images.githubusercontent.com/6314674/55251167-c4d59c80-5247-11e9-97ba-5a7b89b92638.png)
I will upload a test version to my quickFIlters site shortly.

**Comment by El-Pazzo** [comment] 2019-03-29 17:51
Hi,
Yes, I checked that several times. For some reason at home the addon is in English and there it works fine. Only in the office where the addon is in German (for whatever reason).

regards,
Pascal

**Comment by RealRaven2000** [comment] 2019-03-29 18:17
You could check Javascript error console (CTRL+SHIFT+J) when opening the edit filter dialog. Which version of Thunderbird are you running?

**Comment by RealRaven2000** [comment] 2019-03-29 18:21
Try the latest version from here, as well please:
http://downloads.mozdev.org/quickfilters/FiltaQuilla-1.5pre62.xpi

**Comment by El-Pazzo** [comment] 2019-03-29 21:55
latest version
I'll only be able to check it on Monday.

**Comment by El-Pazzo** [comment] 2019-04-01 11:44
Hi RealRaven,

test version does not have any impact. Verzeichnisname is still missing in filter drop down and for existing filters Verzeichnisname is greyed out.

Javascript console does not contain anything about filtaquilla.

**Comment by RealRaven2000** [comment] 2019-04-01 12:21
weird - any errors when you open the edit filter rules dialog? check the troubleshooting guide and console² here: http://quickfolders.org/support.html
(If you configure console² for xul, chrome + JS errors, you may see more)

**Comment by El-Pazzo** [comment] 2019-04-01 12:51
I now get an xml error:

Mon Apr 01 2019 14:46:37
Warnung: Trying to re-register CID '{f2809396-1cd1-12b2-841b-8e15f007c699}' already registered by jar:file:///C:/Users/Translating-IT/AppData/Roaming/Thunderbird/Profiles/p90zbpcy.default/extensions/junquilla@mesquilla.com.xpi!/components/inheritPane-service.js.
Quelldatei: jar:file:///C:/Users/Translating-IT/AppData/Roaming/Thunderbird/Profiles/p90zbpcy.default/extensions/filtaquilla@mesquilla.com.xpi!/chrome.manifest
Zeile: 14

**Comment by RealRaven2000** [comment] 2019-04-04 10:24
I suggest uninstalling filtaquilla and resetting the config string mesquillaInheritedProperties, then install again., not sure what's happening with the registration of that UID, I haven't changed anything there

**Comment by RealRaven2000** [comment] 2019-04-04 10:25
I suggest uninstalling filtaquilla and resetting the config string mesquillaInheritedProperties, then install again., not sure what's happening with the registration of that UID, I haven't changed anything there

**Comment by El-Pazzo** [comment] 2019-04-09 12:01
Hi RealRaven,
How can I reset the properties?

**Comment by El-Pazzo** [comment] 2019-04-09 12:13
found it in about:config

**Comment by RealRaven2000** [comment] 2019-04-09 19:34
You can only set your whole Thunderbird to English. Download the English Language pack and enable it:
https://ftp.mozilla.org/pub/thunderbird/releases/60.6.1/win32/xpi/en-US.xpi
in about:config, set
intl.locale.requested = en-US
Thunderbird will then use the english locales of all Add-ons (where available)
But i am doubtful it will change anything it's not an error caused by locale strings...

**Comment by El-Pazzo** [comment] 2019-04-10 12:53
was worth a try, but you were right. It did not change anything

**Comment by RealRaven2000** [comment] 2019-04-10 15:58
I answered a private email from you, but it bounced back with "Message rejected". Can you provide an alternative email to answer to?

Alternatively here is the text

> > Would it be possible to create an addon that automatically adds a certain text to the email address of To-field (and optionally CC and BCC (both CC and BCC being activated via a box in settings if needed)) if user clicks on reply, reply to all or forward?

> what exactly did you have in mind? A text that is added to every address when you type a new email? or just another email address added? Partly, SmartTemplate⁴ can do similar stuff, have a look at this:

http://smarttemplate4.mozdev.org/premium.html#headerManipulation

currently you could have a look at the following the functions:

    %header.append(to,"text")% = Append Address to to
    %header.delete(to,"text")% = remove address from to (I haven't tested this case)
    %header.set(to,"abc@de.com")% = Replace recipient with email address

maybe the can be extended in some useful way? Also check out my YouTube channel for some videos on how to use SmartTemplate⁴: https://youtu.be/Iah85SdtqNE

Here is a list of introductory videos for SmartTemplate⁴: https://www.youtube.com/watch?v=Rk-T465fkEw&list=PLApv7QYQO9nQ2Jn9zmfh4-RS87h6Qu3wW

writing a new Add-on would take a lot of time, so I am not currently in a position to quote you a price on this (but it would take quite a few days to write one from scratch) - so I am more inclined to look at how my existing Add-ons might be usefully modified if the functionality was a matching enhancement for it. SmartTemplate⁴ might just be the right Add-on to do this, depending on what exactly you have in mind.

Another Add-on of mine (QuickFolders) has an advanced "per-folder" setting where you can prefill the from and to addresses when you write a new email from that folder:

https://i.imgur.com/74Ov1Cs.png

(note this is a setting in a QuickFolders tab, pointing to a folder called SmartTemplates, but it is not functionality of SmartTemplate⁴ - it's a QuickFolders Pro setting) - that may be another candidate for doing something like you have in mind. Per folder may be even more useful.

**Comment by El-Pazzo** [comment] 2019-04-10 20:10
Hi,

I guess it has to do with the gmail address. We get so much spam from gmail (and none of our clients uses gmail address but company domains) that our admins decided to reject gmail addresses for all our mail servers. I just added an exception for your address but I'm not sure whether whitelist goes before blacklist. :(

I started playing around with SmartTemplate4 a bit but could not yet achieve what I need:

If I hit reply address a.b@mailprovider.com in from field should become a.b@mailprovider.com.sometext.com in to field of mail to send.

I need this for some online solution I use which needs some text appended to its mail address whenever I reply from a specific account and it's quite nagging to have to append it manually everytime. Furthermore if you write a few hundred mails per week you tend to forget to add it every time as not all accounts need this.

so maybe something like  %header.set(to,"%to(mail)%.sometext.com")% would help me

**Comment by El-Pazzo** [comment] 2019-04-15 17:54
Hi RealRaven,

It's getting stranger every day. ;) 

Today I saw that the option Folder name (Verzeichnisname) does not work for only a few filters. For others it works fine and it shows up in the dropdown list.
If I clone the faulty filters and save them, Folder name then works like a charm and can also be selected in the dropdown for these filters.

regards,
Pascal

**Comment by RealRaven2000** [comment] 2019-04-15 18:09
If you haven't yet, can you try installing my Add-on quickFilters and the "Debug" button (green bug) on the filters list? This fixes issues with filters that do only run manually. (may be worth a shot)
https://i.imgur.com/VYX3xoK.png

**Comment by El-Pazzo** [comment] 2019-04-16 15:47
as the filter now work due to the trick described above, I cannot get any further debugging info with this tool, but I'll keep it for future usa.

**Comment by haka61** [comment] 2020-01-19 11:08
Hi,
I have TB 68.4.1 32-Bit and Filta Quilla 2.0, German Versions. I tried to detach attachements as shown below.
![grafik](https://user-images.githubusercontent.com/60062236/72679873-e98b5100-3ab3-11ea-90a8-ca62d5d4e784.png)
For every attachement the line in the protocol ends with "Anhänge speichern in" but no folder name.
The attachement extractor works fine.

Regards haka61

**Comment by RealRaven2000** [comment] 2020-01-19 12:35
You can enable debug mode to see if there is any info in the javascript error console.

To enable logging, open FQ settings on the "About FiltaQuilla / Help" tab and check the Debug box:

![image](https://user-images.githubusercontent.com/6314674/72681025-cbbfeb00-3ab7-11ea-8576-712bf2ca86b5.png)

To view the log open Tools / Developer Tools / Error Console  (Ctrl+Shift+J). (Extras / Entwickler Werkzeuge / Fehlerkonsole). I advise resetting all output before you carry out the filter operation so you get a cleaner log.

**Comment by haka61** [comment] 2020-01-20 14:05
Hi RealRaven,
thank you for the tip. 
In the error console Iget now:

FiltaQuilla 13:37:40.250  [390634 ms]   
saveAttachment() - target directory exists:
C:\Kirrung
FiltaQuilla.saveAttachment - converting message headers failed.
Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIMsgMessageService.streamMessage]
uncaught exception: 2147746065 autosync.jsm:251:30

and in the filter protocol:
[20.01.2020, 13:37:40] Filter "Fotoabtrennung" auf die Nachricht web51p1@alinso.de - SECACAM am 20.01.2020, 13:37:42 angewendet Anhänge speichern in 

but the attachements are not stored in the target directory.

TIA haka61

**Comment by RealRaven2000** [comment] 2020-01-20 21:38
> FiltaQuilla 13:37:40.250 [390634 ms]
> saveAttachment() - target directory exists:
> C:\Kirrung
> FiltaQuilla.saveAttachment - converting message headers failed.
> Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIMsgMessageService.streamMessage]

thanks. so that 0x8000400 is a common error that can occur in lots of cases - it's thrown by the underlying Thunderbird code, so there is not much I can do about it, try running the filter after junk qualification.

**Comment by haka61** [comment] 2020-01-21 13:17
thanks.
But it works fine, if I start the filter manually as shown below.
![grafik](https://user-images.githubusercontent.com/60062236/72807948-c6e66d00-3c58-11ea-9177-4093908cbb43.png)

**Comment by RealRaven2000** [comment] 2020-01-21 13:40
> thanks.
> But it works fine, if I start the filter manually as shown below.

That points to a bug in Thunderbird. FiltaQuilla does the same thing, it streams the attachment from the body using an internal Thunderbird command. I think it's obviously just dangerous during/after "get mail" - my guess is it mainly affects IMAP Inboxes. It is possible that the message is just not in a "ready state" to be streamed yet, even if you have selected the option 
"[x] Keep messages in all folders" in the Syunchronizingation & Storage settings tab:

![image](https://user-images.githubusercontent.com/6314674/72809082-d4005d80-3c52-11ea-8f8d-b1abe6e1c96e.png)

Also there is some positive influence on the attachment stability using the option to run filters after Junk Classification, which also points to a timing problem:
![image](https://user-images.githubusercontent.com/6314674/72809212-1e81da00-3c53-11ea-9100-2730b51f4208.png)

also let's focus at one thing at a time, attachments are discussed in issue #4

**Comment by haka61** [comment] 2020-01-21 14:52
thanks.
I had all Options like you showed them.
I think, you are right, it's a synchronisation problem.

**Comment by RealRaven2000** [comment] 2024-02-21 13:09
I am closing the issue for now, feel free to reopen if it is still a problem in 115.

**Closed by RealRaven2000** 2024-02-21 13:09 UTC
