### ISSUE TITLE
UNC-Path of Attachment is not corretly saved

### ISSUE THREAD

**Issue by HeinePotsdam** [RealRaven2000/FiltaQuilla#140] opened 2021-12-14 09:27 UTC
Attachments saving to "\\SERVER\..." will work, but after restart Thunderbird the path is "\SERVER\...".
(two backslashes to one backslash)
And this will not work anymore.

TB 91.4.0
FQ 3.2

**Comment by RealRaven2000** [comment] 2021-12-14 15:58
duplicate of #79 - please add your comments there.

**Closed as completed by RealRaven2000** 2021-12-14 15:58 UTC
