### ISSUE TITLE
Need ability to parametrically set name of attachment save filename

### ISSUE THREAD

**Issue by eyalroz** [RealRaven2000/FiltaQuilla#44] opened 2020-01-06 19:46 UTC
When manually saving files from some entity, you often change their names to fit some naming scheme you're using (e.g. `YYYY-MM NiceTelCo Phone bill.pdf`). When automating this action using FiltaQuilla the saving happens automatically, but it's the original name that's used, which often kind of garbled and meaningless.

The attachment saving should have the possibility of filename generation, using fields/data from multiple sources: The attachment's name, the message headers, the folder, the account, the time and date etc. This could be designed to be  similar to the (re)naming mechanisms we have in media file meta-data editors like [EasyTag](https://help.gnome.org/users/easytag/stable/); see the (feature description](https://help.gnome.org/users/easytag/stable/file-rename.html.en) and [some screenshots](https://projects-old.gnome.org/easytag/screenshots.html) (in the "Scannar Window" section).

**Comment by RealRaven2000** [comment] 2024-02-21 12:47
closing as duplicate of #219

**Closed** 2024-02-21 12:47 UTC
Labels: attachments

**Comment by eyalroz** [comment] 2024-02-21 15:17
@RealRaven2000 : Doesn't look like a dupe, at least not by the title and initial request of #219. If anything, that should be closed as a sub-issue of this one.

**Comment by RealRaven2000** [comment] 2024-02-21 16:35
> @RealRaven2000 : Doesn't look like a dupe, at least not by the title and initial request of #219. If anything, that should be closed as a sub-issue of this one.

I know, but the discussion there has matured and included format components beyond time only, e.g. %date%, %time%, %fromMail%, %subject%, %filename%

Can you add what else you would like as possible components there, without having to chase that up on an external website?
