### ISSUE TITLE
New action: Autoprint attachments

### ISSUE THREAD

**Issue by xXElendielXx** [RealRaven2000/FiltaQuilla#38] opened 2019-12-18 10:00 UTC
Hello there,

it would be nice if there is a feature for the next version to print automatically the attachments from a mail. 

Thanks you

**Comment by furicle** [comment] 2020-06-22 13:14
FWIW, I'm doing this now on Mac with a service that watches the folder where TB saves the attachment, and prints whatever shows up there.
Only works for some file types, but good enough for my purposes...

**Comment by githubphantomas** [comment] 2020-12-18 11:02
Hej everybody, I would like to support this feature as well. This would be really helpful since there is (as far as i know) no possibility to print attachments automatically with Thunderbird. [In contrast: Several paid add-ons are available for Outlook]. Print only PDF-Files is maybe a meaningful beginning.

Hallo zusammen, ich möchte gerne diesen Wunsch unterstützen. Das wäre wirklich hilfreich, weil es (soweit ich weiß) keine Möglichkeit gibt Anhänge automatisch zu drucken in Thunderbird. [Im Gegensatz dazu gibt's für MS Outlook mehrere bezahlte Add-Ons.] Erstmal nur den Druck von PDF-Dateien zu ermöglichen ist vielleicht erst einmal ein sinnvoller Start. Viele Grüße!

**Comment by RealRaven2000** [comment] 2022-01-16 16:06
duplicate of #62

**Comment by RealRaven2000** [comment] 2022-07-31 10:00
My comment from #162:

> This is potentially very difficult as **Thunderbird itself has no concept of what the contents of an attached file type** (such as a word document or pdf file) is. It would have to rely on a shell command to tell the operating system to use the associated program (such as Microsoft word or adobe reader) to open and print the file. Or maybe there is a shell print commando.
>
> Bear in mind that shell command my be prohibited in future versions of Thunderbird as they have too much power working in the operating system, Thunderbird 78 moves towards API-operated "Mail extensions" which closes the door to low level programming interfaces such as XPCOM. So it may not even be possible in the future unless we ask the Thunderbird core team to create a web extensions API for this purpose.
>
> I think a starting point for this will be:
>
> https://thunderbird-webextensions.readthedocs.io/en/68/messages.html#messages-messagepart

Note: the conversion to a web experiment (wx) was done, so we can still use legacy code.

![image](https://user-images.githubusercontent.com/6314674/182020850-af51dda2-a766-415e-bf7a-249c4d4c0cbb.png)

As we can see, Thunderbird itself only can give you options to save / detach the file or open it with the application that is registered on the OS. I think what would we need is an external app to print it (not Thunderbird) so it would need at least a command line as a parameter - e.g. 

https://community.adobe.com/t5/acrobat-reader-discussions/print-with-command-line/td-p/11971108

This one assumes that the pdf exists as file so it needs to be saves first. Again, we need some message from the OS for when the file has finished saving (not sure if save attachment is currently running synchronously, which may potentially hang the main thread and block thunderbird UI while it does filter operations) - then tell adobe read to open the file and print.

**Comment by RealRaven2000** [comment] 2022-08-04 10:19
So in Thunderbird (as it is derived from Firefox) there is an internal pdf viewer, which should be able to print. Maybe we can change the goalpost and just have "print pdf attachments" instead?

**Comment by furicle** [comment] 2022-08-29 13:07
Well, print only certain types is a given.  For instance, you don't want it trying to print an .iso or .mp3 :-)

My home built script calls `file`  expands .zip and runs winmail.dat thru tnefparse, then it only prints pdf, tiff, and txt and ignores the rest.

**Comment by mannebk79** [comment] 2024-02-07 09:48
how about you utilize the same as the explorer context menue for printing?
Or cooperate with foxit, it got a total silent printing option.

we got a bunch of suppliers, that send invoice via email, i want it to be stored, works with filtaquilla, i want it out of the mail inbox, works with filtaquilla, thats awesome thanks.

but printing is a real PITA.

We are talking about 100 to 120 invoices a day. we just need it in the ring binder for tax audits and in case we loose the storage, even with backup thats a posibility, well we could lose those ringbinders too. but then, both at the same time is unlikely.

for this amount, we basically have a part time worker doing nothing else.

so please, find a solution.

**Comment by RealRaven2000** [comment] 2024-02-07 11:50
> Well, print only certain types is a given. For instance, you don't want it trying to print an .iso or .mp3 :-)
> 
> My home built script calls `file` expands .zip and runs winmail.dat thru tnefparse, then it only prints pdf, tiff, and txt and ignores the rest.

would you be kind and share the script for the other members on the thread?

**Comment by mannebk79** [comment] 2024-02-07 11:59
here are some reported working solutions.

https://superuser.com/questions/1418114/print-email-attachment-from-specific-sender-automatically

im going for the foxit, will report back

**Comment by RealRaven2000** [comment] 2024-02-21 11:23
> here are some reported working solutions.
> 
> https://superuser.com/questions/1418114/print-email-attachment-from-specific-sender-automatically
> 
> im going for the foxit, will report back

ok, I will mention the request for printing pdfs to Christopher Leidigh tomorrow, since we have integrated PrintingTools NG, I believe that could potentially access the attachment to print it.

**Comment by mannebk79** [comment] 2024-02-21 11:30
That would be really awesome thanks. Your efforts are highly appreciated.

**Comment by RealRaven2000** [comment] 2024-02-21 12:13
> That would be really awesome thanks. Your efforts are highly appreciated.

@mannebk79 @githubphantomas  @xXElendielXx 
I will mark this as duplicate and continue the issue at #198 - please follow there (just leave an emoji / thumbs up or a comment there to be notified) - sorry for taking so long but at least there is an Add-on that can do this manually, so it shouldn't be too hard to integrate via cooperation.

**Closed by RealRaven2000** 2024-02-21 12:13 UTC
Labels: enhancement, printing

**Comment by furicle** [comment] 2024-02-29 21:27
> > Well, print only certain types is a given. For instance, you don't want it trying to print an .iso or .mp3 :-)
> > My home built script calls `file` expands .zip and runs winmail.dat thru tnefparse, then it only prints pdf, tiff, and txt and ignores the rest.
> 
> would you be kind and share the script for the other members on the thread?

It's just a hacked up bash script, with a bunch of company specific stuff in there
 (print payables stuff here, receivables over there, figlet cover pages so people know its a bundle x pages long, stuff like that)

The heart of it is below, not sure that's useful really.

```bash
function print_invoices {
    local FROMFOLDER="$1"
    local DESTPRINTER="$2"

    # separate out extension
    for file in "$FROMFOLDER"/* ; do
        # a .DS_Store file is ignored
        # So the ls -A counts it, but this test passes and it just does end of line...

        if [ "$file" == "$FROMFOLDER/*" ] ; then
            logger -t printMe.sh '\--- end of line ---'
            continue;
        fi

        logger -t printMe.sh "file $file" ;
        ext=${file##*.} ;
        logger -t printMe.sh "file extension $ext" ;

    # decode if winmail.dat and toss the winmail.dat file
        if [ "$(basename "$file")" == "winmail.dat" ] || [ "$(basename "$file")" == "WINMAIL.DAT" ]  ; then
            logger -t printMe.sh 'found winmail.dat' ;
            /usr/local/bin/tnefparse -a "$file" ;
            logger -t printMe.sh "moving $file to $TOFOLDER" ;
            mv -v "$file" "$TOFOLDER" ;
            continue ;
        fi

    # unzip if zip file and toss the zip file
        if [ "$ext" == "zip" ] || [ "$ext" == "ZIP" ]  ; then
            logger -t printMe.sh 'found zipped file' ;
            /usr/bin/unzip -j "$file" ;
            mv -v "$file" "$TOFOLDER" ;
            logger -t printMe.sh "moving $file to $TOFOLDER" ;
            continue ;
        fi

    # print pdfs then toss them
        if [ "$ext" == "pdf" ] || [ "$ext" == "PDF" ]  ; then
            logger -t printMe.sh 'found pdf file' ;
            lp -d "$DESTPRINTER" -o sides=one-sided -o fit-to-page -o media=letter "$file" ;
            logger -t printMe.sh "moving $file to $TOFOLDER" ;
            mv "$file" "$TOFOLDER" ;
            continue ;
        fi

    # print text or tiff files then toss them
        case $(file -b --mime-type - < "$file" ) in
            (text/*)
                logger -t printMe.sh "found text file"
                /usr/sbin/cupsfilter "$file" | lp -d "$DESTPRINTER" -o sides=one-sided -o fit-to-page -o media=letter ;
            logger -t printMe.sh "moving $file to $TOFOLDER" ;
            mv "$file" "$TOFOLDER" ;
            continue ;
        esac

    # print text or tiff files then toss them
        case $(file -b --mime-type - < "$file" ) in
            (image/tiff)
                logger -t printMe.sh "found tiff file"
                /usr/sbin/cupsfilter "$file" | lp -d "$DESTPRINTER" -o sides=one-sided -o fit-to-page -o media=letter ;
            logger -t printMe.sh "moving $file to $TOFOLDER" ;
            mv "$file" "$TOFOLDER" ;
            continue ;
        esac

    # dunno what the heck it was, print a note, delete it too
    local BADFILENAME=$(basename $file)
    local BADFILEMESSAGE=$(printf "Non printable file found! \n \n $BADFILENAME")
    local BIGCONTENTS="$(figlet -w 75 -c "$BADFILEMESSAGE")"
    local UNPRINTABLEPAGE="unprintablepage.txt"
    cat > "$UNPRINTABLEPAGE" <<End-of-message
```
