### ISSUE TITLE
Move Later failed

### ISSUE THREAD

**Issue by IPenkov** [RealRaven2000/FiltaQuilla#45] opened 2020-01-07 12:32 UTC
Filter 'Move later' failed to move mails to diffrent folder with error  Message from filter "Azure": custom action failed to apply

thunderbird version 68.3.1 (64-bit) / FiltaQuilla 2.0

![image](https://user-images.githubusercontent.com/7457582/71895596-21140800-315a-11ea-8dd0-197d743aab9c.png)

![image](https://user-images.githubusercontent.com/7457582/71895619-31c47e00-315a-11ea-8872-9fe34e2fab22.png)

**Comment by RealRaven2000** [comment] 2020-01-07 13:27
I would start trouble shooting by having a look at the JS Error console - Tools > Web Developer. 

I am not quite sure how move later works, can you invoke the error by executing the "Run Filters on Folder" command? (Tools menu)

**Comment by IPenkov** [comment] 2020-01-07 14:14
TypeError: MailUtils.getFolderForURI is not a functionfiltaquilla.js:812:35

run filter error

**Comment by RealRaven2000** [comment] 2020-01-07 14:26
> TypeError: MailUtils.getFolderForURI is not a functionfiltaquilla.js:812:35
> chrome://filtaquilla/content/filtaquilla.js:812:35
> run filter error

ok, that definitely helps! Do you know what exactly "move later" does? Not quite sure how "Later" is supposed to work quantitatively.

**Comment by IPenkov** [comment] 2020-01-07 14:39
Actually I think it is moving mail to a folder with a delay. 

There is an issue combining 'move' and 'do not notify'(I think it is related to the order of execution). So I use 'Move later' instead of 'Move'.

**Comment by alanmead** [comment] 2020-01-24 22:27
"Move later" is also failing for me using TB 68.4.2 (and whatever version was previous). As I think you know, this enables a "Move Later" action in a filter which executes the move after a small delay (like 1 second). 

For me (and I think for a lot of people), this works around a bug (or an unintended feature). In my case, I want to move mailing list emails to a folder and ignore them (not be notified). If I use TB's standard "move" action in the filter, the notification still rings (we can find an explanation online, but for which ICRRN -- It has something to do with how TB processes these. The notification is generated when an email appears in the folder and it doesn't know about the "no notification" in Inbox). So, in my case, "move later" allows the "no notification" to fire while the email is in Inbox, and then a second later it's moved to the folder. 

But the point is that what "move later" **really** does is to work around some unintended features of TB. Online, I see someone using it to make saving attachments work. The "move later" was a way to work around some TB issues. Obviously, another option would be to have TB fix the underlying issues, but I think they are complex. It would be nice if "Move Later" worked again.

It might also be worth noting that when it stopped working for me, it was very not apparent. The filter stopped at the error. I had forgotten completely that I had to install filtaquilla. So, the fact that IPenkov and I are the only ones complaining, does not mean that this issue is not affecting a lot of people. For me, I could see the emails that are supposed to be moving sitting in my Inbox. If you were expecting an attachment to be saved, you might be losing attachments. This problem might be kind of a big deal for some users who maybe haven't found there way here to complain yet.

**Comment by dtrckd** [comment] 2020-04-15 08:56
I confirm this issue.
Version debian stable / 1:68.7.0-1~deb10u1

**Comment by Moerkman** [comment] 2020-10-26 21:42
Confirmed. Would be a good Workaround to my Problem #73

**Comment by furest** [comment] 2020-11-30 22:58
I really wanted the "no notification" to work for me so I found by digging a little bit that the "getFolderForUri" function had been renamed "getExistingFolder" in TB 67 : https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_63

I got the "move later" and thus the "no notification" filter to work by renaming the function in the source code.

Maybe this could do it into the next release candidate? I may be wrong but that's an easy win for a useful feature.

**Comment by RealRaven2000** [comment] 2020-12-01 10:12
> getExistingFolder

Thanks - I remember I used this pattern before in QuickFolders:
```
let folder = (MailUtils.getExistingFolder) ? 
     MailUtils.getExistingFolder(aActionValue, false) : MailUtils.getFolderForURI(aActionValue, false);
```
So I am also going to back-port that into the older version for thunderbird 68 (master branch)

**Comment by RealRaven2000** [comment] 2020-12-10 13:41
Closing as resolved with the following releases
https://github.com/RealRaven2000/FiltaQuilla/releases/tag/2.1.2
https://github.com/RealRaven2000/FiltaQuilla/releases/tag/3.0.2.0

**Closed by RealRaven2000** 2020-12-10 13:41 UTC
