### ISSUE TITLE
print automation is not working with Thunderbird Version 91.2.1

### ISSUE THREAD

**Issue by ASMarvin** [RealRaven2000/FiltaQuilla#130] opened 2021-10-26 08:14 UTC
We use FilaQuilla to automatically print orders that come via email. Normally the addon should print emails automatically and mark them as read afterwards. With the latest version of Thunderbird (91.2.1, release October 21) the addon is not printing mails anymore. It marks them as read but wont print them.

 I attached the log from the error console as it may help to fix the issue.
[Error Console.txt](https://github.com/RealRaven2000/FiltaQuilla/files/7416310/Error.Console.txt)

**Comment by ToaKamate** [comment] 2021-10-26 15:49
Exact same issue here except worse and I'm still on Thunderbird 78.14.0 (64-bit) - I specifically don't do auto updates just for this reason. Not only does it not automatically print our orders, but it has added the Print option to Actions in the Filters dialog about 40 times (see screenshot).  Also, it is totally messing up almost all new Inbox messages for the email address the filter applies to.  I was missing a bunch of orders and as soon as I removed the Add-on - they all magically appeared in the Inbox
![2021-10-26 09_44_24-Filter Rules](https://user-images.githubusercontent.com/48141166/138914656-392c20fe-294e-47c6-bf9a-db15f394a12d.png)
.

**Comment by RealRaven2000** [comment] 2021-10-28 17:48
So I tested this here with a very simple filter and FiltaQuilla v 3.2 installed, worked for me on Thunderbird 78.14 - here is  my filter definition (based on a tag for testing):

![image](https://user-images.githubusercontent.com/6314674/139308033-72d3aa08-34e4-43ec-8dbb-18ee8bf417a2.png)


My output on JS error console after running the filter (manually) on 2 highlighted mails:

```
Queue filter request to print message: [filtaquilla] plain text - fq regex test PS -- 48x48
Finished printing message: [filtaquilla] plain text - fq regex test PS -- 48x48
Queue filter request to print message: Help strengthen the security of your Google Account
Finished printing message: Help strengthen the security of your Google Account
```

The added items in the editor could happen if you went to the filtaquilla settings repeatedly (not by running the filter). Can you check your JS error console?

Ctrl+Shift+J should bring it up.

**Comment by eastermann** [comment] 2021-10-29 06:36
> So I tested this here with a very simple filter and FiltaQuilla v 3.2 installed, worked for me on Thunderbird 78.14 - here is my filter definition (based on a tag for testing):
> 
> ![image](https://user-images.githubusercontent.com/6314674/139308033-72d3aa08-34e4-43ec-8dbb-18ee8bf417a2.png)
> 
> My output on JS error console after running the filter (manually) on 2 highlighted mails:
> 
> ```
> Queue filter request to print message: [filtaquilla] plain text - fq regex test PS -- 48x48
> Finished printing message: [filtaquilla] plain text - fq regex test PS -- 48x48
> Queue filter request to print message: Help strengthen the security of your Google Account
> Finished printing message: Help strengthen the security of your Google Account
> ```
> 
> The added items in the editor could happen if you went to the filtaquilla settings repeatedly (not by running the filter). Can you check your JS error console?
> 
> Ctrl+Shift+J should bring it up.

The way back to an older Version, works for me to. 
Thanks

**Comment by ASMarvin** [comment] 2021-10-29 08:10
> > So I tested this here with a very simple filter and FiltaQuilla v 3.2 installed, worked for me on Thunderbird 78.14 - here is my filter definition (based on a tag for testing):
> > ![image](https://user-images.githubusercontent.com/6314674/139308033-72d3aa08-34e4-43ec-8dbb-18ee8bf417a2.png)
> > My output on JS error console after running the filter (manually) on 2 highlighted mails:
> > ```
> > Queue filter request to print message: [filtaquilla] plain text - fq regex test PS -- 48x48
> > Finished printing message: [filtaquilla] plain text - fq regex test PS -- 48x48
> > Queue filter request to print message: Help strengthen the security of your Google Account
> > Finished printing message: Help strengthen the security of your Google Account
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The added items in the editor could happen if you went to the filtaquilla settings repeatedly (not by running the filter). Can you check your JS error console?
> > Ctrl+Shift+J should bring it up.
> 
> The way back to an older Version, works for me to. Thanks

Cant go back to an older version. What should I do now? How can it work on Version 91.2.1.?

**Comment by RealRaven2000** [comment] 2021-10-29 11:01
> > 
> > 
> > The way back to an older Version, works for me to. Thanks
> 
> Cant go back to an older version. What should I do now? How can it work on Version 91.2.1.?

Don't. (one of the OPs said the problem was on 78). I will test again on 91...

**Comment by RealRaven2000** [comment] 2021-10-29 11:04
Here we go, one quick look at JavaScript console reveals that the interface `nsIMsgPrintEngine` doesn't exist anymore in Thunderbird 91. Probably renamed or completely recoded:

![image](https://user-images.githubusercontent.com/6314674/139423915-507edb07-40c0-455f-ae0f-ee5147958f51.png)

**Comment by RealRaven2000** [comment] 2021-10-29 11:10
Finding the new print method in c-c is true needle in a haystack stuff...

https://searchfox.org/comm-central/source/mail/components/addrbook/content/aboutAddressBook.js#2183
https://searchfox.org/comm-central/search?q=printM&case=true&path=

If you do your on research, please bear in mind that any results containing "suite"  is irrelevant as this is just legacy code from SeaMonkey.

**Comment by RealRaven2000** [comment] 2021-10-29 11:11
Found PrintSelectedMessages, hopefully I can work from there:

https://searchfox.org/comm-central/source/mail/base/content/mail3PaneWindowCommands.js#1538

**Comment by ToaKamate** [comment] 2021-10-29 15:44
OK, very strange.  I might have to wait until you get things fixed for the latest version of TBird and chance upgrading.  When I test the filter I don't get any errors, in fact the filter log shows it ran fine - however nothing is sent to the default printer queue. 

 [10/29/2021, 9:34:24 AM] Applied filter "Print" to message from baker@xxxxxx - VCheck Renewal Order: Approved at 10/25/2021, 1:46:11 PM Print

[10/29/2021, 9:34:24 AM] Applied filter "Print" to message from Vcheck Payment System <noreply@securevcheck.com> - Vcheck Generated from Allen Financial Insurance Group at aquinte@xxxxxx at 10/26/2021, 10:57:25 AM Print 

I'll try upgrading to version 90.0 and hope it doesn't break my other add-ons.

**Comment by ToaKamate** [comment] 2021-10-29 16:19
Upgraded to v. 90.0.  Now I do get an error when trying to run Print:
Uncaught TypeError: Ci.nsIMsgPrintEngine is undefined
    _printNextMessage chrome://filtaquilla/content/filtaquilla.js:632

**Comment by MikeGarfield** [comment] 2021-11-04 13:02
Upgraded to 91.3.0 and the automation print doesn´t work since 91.2.1. Is there an improvement in sight?

**Comment by ASMarvin** [comment] 2021-11-05 08:12
> Upgraded to 91.3.0 and the automation print doesn´t work since 91.2.1. Is there an improvement in sight?

He is on it as far as I could see.

**Comment by dougbitt** [comment] 2021-11-08 17:46
> > Upgraded to 91.3.0 and the automation print doesn´t work since 91.2.1. Is there an improvement in sight?
> 
> He is on it as far as I could see.

How do we know? an ETA?

**Comment by RealRaven2000** [comment] 2021-11-24 17:37
Still working on this - I am trying to use the global `PrintUtils` object, but missing the method `loadPrintBrowser` (which does exist and is used in Tb Core code). So far I can only print the message that is currently selected which of course is useless for filters. @TbSync said he is working on a print API which I am hoping to land in Thunderbird 91.4 - we will see!

**Comment by MikeGarfield** [comment] 2021-11-25 21:25
> Still working on this - I am trying to use the global `PrintUtils` object, but missing the method `loadPrintBrowser` (which does exist and is used in Tb Core code). So far I can only print the message that is currently selected which of course is useless for filters. @TbSync said he is working on a print API which I am hoping to land in Thunderbird 91.4 - we will see!

Isn´t it possible, to use the popup-link if you get a new message to select the correct filtered message, and then to print?

**Comment by RealRaven2000** [comment] 2021-11-26 11:13
> > Still working on this - I am trying to use the global `PrintUtils` object, but missing the method `loadPrintBrowser` (which does exist and is used in Tb Core code). So far I can only print the message that is currently selected which of course is useless for filters. @TbSync said he is working on a print API which I am hoping to land in Thunderbird 91.4 - we will see!
> 
> Isn´t it possible, to use the popup-link if you get a new message to select the correct filtered message, and then to print?

That's a bit of a can of worms - selecting random messages in the middle of filters running (automatically) my be disruptive while you are reading other messages, Also it is not guaranteed that it works if you are on a different tab such as Calendar or a single email tab, so I would rather find a way to do it in the background.

**Comment by RealRaven2000** [comment] 2021-12-01 10:00
Here is just some hope, there are build candidates for 91.4

https://archive.mozilla.org/pub/thunderbird/candidates/91.4.0-candidates/build1/

I was just able to print one message by using the "Run Filters" button on the Filter list dialog in the win32 version.

Will do some more testing over the weekend.

**Comment by Eibihp** [comment] 2021-12-05 16:59
*

**Comment by archfiddler** [comment] 2022-01-11 16:16
running 91.4.1 (32 bit) .... removed other add-ons, simplified filters etc but...... not a glimmer of printing here. Filter log registering filter being applied but no effect.

**Comment by RealRaven2000** [comment] 2022-01-16 16:01
New version to test - appears to work in TB 91.5 here:

[filtaquilla-3.2.1pre21.zip](https://github.com/RealRaven2000/FiltaQuilla/files/7877324/filtaquilla-3.2.1pre21.zip)

to install, download the zip file (don't unpack) and drag into Thunderbird Add-ons Manager.

**Comment by archfiddler** [comment] 2022-01-17 09:36
Woohoo! working here too. Thanks so much for this. Will log any issues

**Comment by ToaKamate** [comment] 2022-01-17 18:21
Did not work for me.  However, I'm using TB 91.3 (32-bit so Quickbooks can use it).
Navigated to mailbox:///C:/Users/TJ/AppData/Roaming/Thunderbird/Profiles/kc3kx7d4.default/Mail/mail.vchecksolutions.com/Inbox?number=297
TypeError: browser is null
PrintingParent.jsm:22:22
TypeError: browser is null
BrowserElementParent.jsm:24:21
Uncaught (in promise) 
Exception { name: "NS_ERROR_GFX_PRINTER_NAME_NOT_FOUND", message: "", result: 2152202242, filename: "chrome://global/content/printUtils.js", lineNumber: 336, columnNumber: 0, data: null, stack: "printWindow@chrome://global/content/printUtils.js:336:36\nstartPrintWindow@chrome://global/content/printUtils.js:295:10\n_printNextMessage@chrome://filtaquilla/content/filtaquilla.js:655:30\n", location: XPCWrappedNative_NoHelper }
printUtils.js:336

**Comment by RealRaven2000** [comment] 2022-01-17 18:52
> Did not work for me. However, I'm using TB 91.3 (32-bit so Quickbooks can use it). Navigated to mailbox:///C:/Users/TJ/AppData/Roaming/Thunderbird/Profiles/kc3kx7d4.default/Mail/mail.vchecksolutions.com/Inbox?number=297 TypeError: browser is null PrintingParent.jsm:22:22 TypeError: browser is null BrowserElementParent.jsm:24:21 Uncaught (in promise) Exception { name: "NS_ERROR_GFX_PRINTER_NAME_NOT_FOUND", message: "", result: 2152202242, filename: "chrome://global/content/printUtils.js", lineNumber: 336, columnNumber: 0, data: null, stack: "printWindow@chrome://global/content/printUtils.js:336:36\nstartPrintWindow@chrome://global/content/printUtils.js:295:10

I checked this against the toolkit / mozilla code here:

https://searchfox.org/mozilla-esr91/source/toolkit/components/printing/content/printUtils.js#295

A little strange as I pass an empty `aObjects` argument which makes me expect the "browser" variable to be irrelevant. Can you try and set up a defauilt printer? What happens when you open a message (just click on it, don;'t even open a tab) and click on File / Print?

**Comment by ToaKamate** [comment] 2022-01-17 19:38
> > Did not work for me. However, I'm using TB 91.3 (32-bit so Quickbooks can use it). Navigated to mailbox:///C:/Users/TJ/AppData/Roaming/Thunderbird/Profiles/kc3kx7d4.default/Mail/mail.vchecksolutions.com/Inbox?number=297 TypeError: browser is null PrintingParent.jsm:22:22 TypeError: browser is null BrowserElementParent.jsm:24:21 Uncaught (in promise) Exception { name: "NS_ERROR_GFX_PRINTER_NAME_NOT_FOUND", message: "", result: 2152202242, filename: "chrome://global/content/printUtils.js", lineNumber: 336, columnNumber: 0, data: null, stack: "printWindow@chrome://global/content/printUtils.js:336:36\nstartPrintWindow@chrome://global/content/printUtils.js:295:10
> 
> I checked this against the toolkit / mozilla code here:
> 
> https://searchfox.org/mozilla-esr91/source/toolkit/components/printing/content/printUtils.js#295
> 
> A little strange as I pass an empty `aObjects` argument which makes me expect the "browser" variable to be irrelevant. Can you try and set up a defauilt printer? What happens when you open a message (just click on it, don;'t even open a tab) and click on File / Print?

WOW, this is weird.  I have a default printer setup in Windows. But something happened in TB - now it will not print anything.  When I try to print something I get the error below.  Any ideas on how to fix this?

Uncaught (in promise) 
Exception { name: "NS_ERROR_GFX_PRINTER_NAME_NOT_FOUND", message: "", result: 2152202242, filename: "chrome://global/content/printUtils.js", lineNumber: 336, columnNumber: 0, data: null, stack: "printWindow@chrome://global/content/printUtils.js:336:36\nstartPrintWindow@chrome://global/content/printUtils.js:295:10\ndoCommand@chrome://messenger/content/mail3PaneWindowCommands.js:917:20\ndoCommand@chrome://messenger/content/mailTabs.js:842:23\ndoCommand@chrome://messenger/content/tabmail.js:581:27\ngoDoCommand@chrome://global/content/globalOverlay.js:123:18\noncommand@chrome://messenger/content/messenger.xhtml:1:12\n", location: XPCWrappedNative_NoHelper }

**Comment by ToaKamate** [comment] 2022-01-17 20:01
> WOW, this is weird. I have a default printer setup in Windows. But something happened in TB - now it will not print anything. When I try to print something I get the error below. Any ideas on how to fix this?

I just posted as a bug on TB forums with more details.  Don't have a clue why TB won't print anything now.  https://support.mozilla.org/en-US/questions/1364777

**Comment by RealRaven2000** [comment] 2022-01-17 20:11
Just joined the Add-on Dev call now, looking at the way Phillippe does this in his CardBook Add-on.

Apparently he creates a hidden browser  window in an element `cardbookPrintContent` and uses the print methods from there. See if I can learn how to do this in fq.

**Comment by RealRaven2000** [comment] 2022-01-17 20:14
John Bieling does a similar thing in mboximport.js

He is using the the service printservice in export-import-tools-ng:

![image](https://user-images.githubusercontent.com/6314674/149832099-b8bd65b0-1a20-4041-aec5-38e755ab67b4.png)

**Comment by MikeGarfield** [comment] 2022-01-17 20:14
in 91.5.0 (32-bit) it works fine also with other filters.

**Comment by ASMarvin** [comment] 2022-01-18 09:17
> in 91.5.0 (32-bit) it works fine also with other filters.

unfortunately it does not work for me on the same version (64-bit). What Im doing wrong? D: 

I downloaded the zip.file and dragged it into the add-ons manager. But it still does not print. It marks as read though, so the filter atleast does something.

**Comment by RealRaven2000** [comment] 2022-01-18 11:49
> > in 91.5.0 (32-bit) it works fine also with other filters.
> 
> unfortunately it does not work for me on the same version (64-bit). What Im doing wrong? D:
> 
> I downloaded the zip.file and dragged it into the add-ons manager. 

Did it give you a message about the installation that you had to click ok on?

![image](https://user-images.githubusercontent.com/6314674/149931814-98438fd2-f99e-4040-9d94-7331c083c0d8.png)

You can generate a debug log using JavaScript Error console:
Tools / Developer Tools / Error Console  (Or Ctrl+Shift+J if you are in WIndows / Linux)

clear the console...
![image](https://user-images.githubusercontent.com/6314674/149932258-6aaf6d5d-a48c-4ff6-a169-a5b4d19f0c50.png)


...then run the message filter. Copy the log text via right-click - Export visible messages to / clipboard:
![image](https://user-images.githubusercontent.com/6314674/149932050-e6e94175-0cbc-491b-862f-bcba20d42a0b.png)

**Comment by ToaKamate** [comment] 2022-01-18 20:17
> > WOW, this is weird. I have a default printer setup in Windows. But something happened in TB - now it will not print anything. When I try to print something I get the error below. Any ideas on how to fix this?
> 
> I just posted as a bug on TB forums with more details. Don't have a clue why TB won't print anything now. https://support.mozilla.org/en-US/questions/1364777

FIXED!  Your new version now works in 91.3 (32-bit).  Went through hell trying to fix the printing issue with TB.  Finally all it took was to clear all the saved print settings in troubleshooting information.

**Comment by ASMarvin** [comment] 2022-01-20 13:24
update: it looks like its also working on the 64-bit version on 91.5.0 for me now! 

Is there a way I can send you a donation or something @RealRaven2000 ?

**Comment by RealRaven2000** [comment] 2022-01-20 16:22
> update: it looks like its also working on the 64-bit version on 91.5.0 for me now!
> 
> Is there a way I can send you a donation or something @RealRaven2000 ?

Yes, here: https://quickfilters.quickfolders.org/filtaquilla.html#donate

**Comment by RealRaven2000** [comment] 2022-01-21 14:27
Fixed in 3.3, officially released today (21/02/22)

**Closed as completed by RealRaven2000** 2022-01-21 14:27 UTC

**Comment by MikeGarfield** [comment] 2022-01-22 15:42
> in 91.5.0 (32-bit) it works fine also with other filters.

but the 3.3 filtaquilla ist not good. they print two times one mail. If comes 2 mails at the same time, it prints only the last one.

if i go back to 3.2.1.pre it´s the same bug. 2 mails at the same time, it prints only the last one.

**Comment by RealRaven2000** [comment] 2022-01-22 16:35
> > in 91.5.0 (32-bit) it works fine also with other filters.
> 
> but the 3.3 filtaquilla ist not good. they print two times one mail. If comes 2 mails at the same time, it prints only the last one.
> 
> if i go back to 3.2.1.pre it´s the same bug. 2 mails at the same time, it prints only the last one.

Do you mean it only prints the one, once, or does it print the same one (twice)? Did it behave differently in 3.1? (I know we cannot test 3.1 with Tb91 now as it is only compatible with TB78)

**Comment by MikeGarfield** [comment] 2022-01-22 19:15
in 3.1 it prints every mail seperately once. before we go to tb91.
Now in 3.3, if 2 mail come at the same time, filtaquilla only prints the 2nd and twice. It prints every mail twice. i hope you can understand me

**Comment by RealRaven2000** [comment] 2022-01-23 13:03
> > in 91.5.0 (32-bit) it works fine also with other filters.
> 
> but the 3.3 filtaquilla ist not good. they print two times one mail. If comes 2 mails at the same time, it prints only the last one.
> 
> if i go back to 3.2.1.pre it´s the same bug. 2 mails at the same time, it prints only the last one.

I am not sure, but it may be caused by the `printNextMessage()` had to be converted into an asynchronous one (otherwise it can't call the asynchronous `function PrintUtils.loadPrintBrowser()`). While I can't reproduce your issue, if you can then you're welcome to test the following:
Here is a quick test version for you.

Not sure if this is going to work, but it calls the function using the keyword `await` which forces it to be executed synchronously (meaning we wait until the funciton is complete before going to the next step of the Script)

[filtaquilla-3.3.1pre5.zip](https://github.com/RealRaven2000/FiltaQuilla/files/7920534/filtaquilla-3.3.1pre5.zip)

**Comment by RealRaven2000** [comment] 2022-01-23 13:13
> in 3.1 it prints every mail seperately once. before we go to tb91. Now in 3.3, if 2 mail come at the same time, filtaquilla only prints the 2nd and twice. It prints every mail twice. i hope you can understand me

hold on. Are you running 3.3 in Thunderbird 78? I may have seen an additional issue for that case...

**Comment by RealRaven2000** [comment] 2022-01-23 13:18
> > in 3.1 it prints every mail seperately once. before we go to tb91. Now in 3.3, if 2 mail come at the same time, filtaquilla only prints the 2nd and twice. It prints every mail twice. i hope you can understand me
> 
> hold on. Are you running 3.3 in Thunderbird 78? I may have seen an additional issue for that case...

never mind. there was just a conversion step from an enum to an array for Tb78, which looked dodgy - in TB78 filter actions are called via `apply()` - where I do the conversion and then call `applyAction()` which is the new format in Tb91. But there is no duplication happening.

```javascript
  self.print =
  {
    //...
    applyAction: function(aMsgHdrs, aActionValue, aListener, aType, aMsgWindow) {
      // print me
      let count = aMsgHdrs.length;
      for (let i = 0; i < count; i++) {
        let hdr = aMsgHdrs[i];
        // no duplicates!
        if (!printQueue.includes(hdr))
          printQueue.push(hdr);
      }
      //... printing code running on printQueue[] Array....
    },
    apply: function(aMsgHdrs, aActionValue, aListener, aType, aMsgWindow)
    {
      let msgHdrs = [];
      for (var i = 0; i < aMsgHdrs.length; i++) {
        msgHdrs.push (aMsgHdrs.queryElementAt(i, Ci.nsIMsgDBHdr));
      }
      this.applyAction(msgHdrs, aActionValue, aListener, aType, aMsgWindow);
    },        
        
```

**Comment by RealRaven2000** [comment] 2022-01-23 18:04
Here is another version  -I had to fix the code path for Tb78 - I applied it to 2 different mails at the same time, it printed both (once only)

[filtaquilla-3.3.1pre13.zip](https://github.com/RealRaven2000/FiltaQuilla/files/7921059/filtaquilla-3.3.1pre13.zip)

should work in both 91 and 78 - just drag into Add-on Manager to test.

**Comment by MikeGarfield** [comment] 2022-01-24 21:52
i use tb91.5.0 and the new fix filtaquilla-3.3.1pre13.zip:

[24.01.2022, 22:42:26] Mitteilung von Filter "Druck der Bestellungen": Applying filter actions failed
[24.01.2022, 22:42:26] Filter run failed

There is no print action in filter

**Comment by RealRaven2000** [comment] 2022-01-24 23:38
Seems like there is a mistake (I wrote async instead of await when calling the printMessage function) - sorry about that - fixed version below:

[filtaquilla-3.3.1pre15.zip](https://github.com/RealRaven2000/FiltaQuilla/files/7929583/filtaquilla-3.3.1pre15.zip)

**Comment by MikeGarfield** [comment] 2022-01-25 12:31
ok the fix is working for twice printing.

The other problem isn´t solved.

Close TB and send 2 mails from other device which print with filtaquilla. Then open TB and look what filtaquilla prints. At my tb it prints only 1 mail of the 2 twice, not each one individually.

**Comment by RealRaven2000** [comment] 2022-01-25 13:15
> Close TB and send 2 mails from other device which print with filtaquilla. 

not sure what you mean - sending from a thunderbird with FiltaQuilla? You expect it to print a sent mail?

> Then open TB and look what filtaquilla prints. At my tb it prints only 1 mail of the 2 twice, not each one individually.

If it's in the inbox (and newly incoming email, with filters running automatically, isn't that exactly the same thing as the first problem? Or are you talking about 2 different Thunderbird programs (e.g. on 2 computers) both printing the same email?

**Comment by MikeGarfield** [comment] 2022-01-25 13:44
Sry for my description.
I print out orders that come in the mail.

For example: I get 3 orders overnight.
When starting work, filtaquilla only prints 1 order three times.

do you understand what my problem is?

**Comment by RealRaven2000** [comment] 2022-01-25 14:17
> Sry for my description. I print out orders that come in the mail.
> 
> For example: I get 3 orders overnight. When starting work, filtaquilla only prints 1 order three times.

OK, so you are saying if you run the filters manually (e.g. using run filters on folder) it prints 3 different mails, but when it runs automatically it prints does the duplication instead - as of 3.3.1 prerelease 15 posted above.

I don't understand why it would behave differently in both cases - as you said first "ok the fix is working for twice printing." - it's exactly the same logic: when the filter is triggered it gets an Array of matching  emails from the built in filtering mechanism - it copies the headers into a queue Array and then removes one after the other while printing.

In your filter log, do you see the first title printer out 3 times or the 3 different mails mentioned instead?
![image](https://user-images.githubusercontent.com/6314674/150993071-73ec187d-1c67-49dd-971a-3579b4822200.png)

I would expect it to list the 2 different mail subjects (with the same time stamp) - as in my test:

```
[23/01/2022, 18:01:38] Applied filter "Dev » FiltaQuilla - Filtaquilla - print test" 
to message from Axel Grude <axel.grude@gmail.com> - Filtaquilla - print test 
at 29/10/2021, 12:01:25 Print
[23/01/2022, 18:01:38] Applied filter "Dev » FiltaQuilla - Filtaquilla - print test" 
to message from Thunderbird Daily-Addons <thunderbirddaily@gmail.com> - Filtaquilla - print test 
at 16/01/2022, 15:50:11 Print 
```

Both filter executions have the same time stamp but refer to 2 different mails. Would be interested if you see the same email title listed three times? (with 3.3.1 prerelease 15)

**Comment by MikeGarfield** [comment] 2022-01-26 14:18
Here is the filter log of testing 3 Orders:

 [26.01.2022, 15:16:27] Filter "Druck der Bestellungen" auf die Nachricht Sushibar Homeservice<bestellung@sushibar-muc.com> - Sushibar Homeservice - Auftrag 76007 am 26.01.2022, 15:15:14 angewendet Ausdrucken

[26.01.2022, 15:16:27] Filter "Druck der Bestellungen" auf die Nachricht Sushibar Homeservice<bestellung@sushibar-muc.com> - Sushibar Homeservice - Auftrag 76008 am 26.01.2022, 15:15:29 angewendet Ausdrucken

[26.01.2022, 15:16:27] Filter "Druck der Bestellungen" auf die Nachricht Sushibar Homeservice<bestellung@sushibar-muc.com> - Sushibar Homeservice - Auftrag 76009 am 26.01.2022, 15:15:42 angewendet Ausdrucken 

3 different orders, but only the **76007** was printed 3times

If i run the filter manually, everything is ok. i get all 3 different orders.

**Comment by RealRaven2000** [comment] 2022-01-26 23:15
> Here is the filter log of testing 3 Orders:
> 
> [26.01.2022, 15:16:27] Filter "Druck der Bestellungen" auf die Nachricht Sushibar Homeservice[bestellung@sushibar-muc.com](mailto:bestellung@sushibar-muc.com) - Sushibar Homeservice - Auftrag 76007 am 26.01.2022, 15:15:14 angewendet Ausdrucken
> 
> [26.01.2022, 15:16:27] Filter "Druck der Bestellungen" auf die Nachricht Sushibar Homeservice[bestellung@sushibar-muc.com](mailto:bestellung@sushibar-muc.com) - Sushibar Homeservice - Auftrag 76008 am 26.01.2022, 15:15:29 angewendet Ausdrucken
> 
> [26.01.2022, 15:16:27] Filter "Druck der Bestellungen" auf die Nachricht Sushibar Homeservice[bestellung@sushibar-muc.com](mailto:bestellung@sushibar-muc.com) - Sushibar Homeservice - Auftrag 76009 am 26.01.2022, 15:15:42 angewendet Ausdrucken
> 
> 3 different orders, but only the **76007** was printed 3times

thanks, this is helpful. THunderbird seems to pass in 3 different messages (otherwise you wouldn't see different log entries) but the filter execution appears to hang on the first one for some unknown reason. I will test it again, now that I have bought more paper for my printer! :)
