### ISSUE TITLE
Printing of only the attachment of some marked emails 

### ISSUE THREAD

**Issue by yarn37235** [RealRaven2000/FiltaQuilla#62] opened 2020-07-01 09:20 UTC
Automatically printing of only the attachment of these above mentioned emails (Invoices, normally as PDF or jpg or doc) on a printer. No printing of the email itself is needed... only the attachment.
(As we still use a paper copy for tax authorities etc).
With these automated functions I would save a lot of time with all these selected emails (Invoices etc).

**Comment by RealRaven2000** [comment] 2020-07-01 16:07
This is potentially very difficult as Thunderbird itself has no concept of what the contents of a file type (such as a word document or pdf file) is. It would have to rely on a shell command to tell the operating system to use the associated program (such as Microsoft word or adobe reader) to open and print the file. Or maybe there is a shell print commando.

Bear in mind that shell command my be prohibited in future versions of Thunderbird as they have too much power working in the operating system, Thunderbird 78 moves towards API-operated "Mail extensions" which closes the door to low level programming interfaces such as XPCOM. So it may not even be possible in the future unless we ask the Thunderbird core team to create a web extensions API for this purpose.

I think a starting point for this will be:

https://thunderbird-webextensions.readthedocs.io/en/68/messages.html#messages-messagepart

but I haven't found much detail here, guess I will have to do the conversion to a web experiment first and then see how we can access this API from a background script. Unfortunately I am new to web extensions so I have to completely relearn programming for Thunderbird

**Comment by RealRaven2000** [comment] 2024-02-21 12:09
Marking as duplicate of #198 - please follow there for updates!

**Closed by RealRaven2000** 2024-02-21 12:09 UTC
Labels: enhancement, printing
