### ISSUE TITLE
"Save Attachments to" save "0 kb" file

### ISSUE THREAD

**Issue by DPappD** [RealRaven2000/FiltaQuilla#195] opened 2022-11-14 13:49 UTC
"Save Attachments to" save "0 kb" file without content!
 
![Képernyőkép 2022-11-14 144836](https://user-images.githubusercontent.com/117909358/201676449-88e9d9e1-ee9d-4970-945d-f33e9d45df72.png)

**Comment by DPappD** [comment] 2022-11-14 13:50
You can see the filter-saved files whit "0 kb" and the self-saved files whit 53 kb etc.

**Comment by RealRaven2000** [comment] 2024-02-21 12:28
marking as duplicate of #247 please follow there for updates. I am currently consolidating a ton of old bugs...

**Closed as completed by RealRaven2000** 2024-02-21 12:28 UTC
Labels: attachments
