### ISSUE TITLE
Automatic printing doesn't work anymore

### ISSUE THREAD

**Issue by m4m-jonas** [RealRaven2000/FiltaQuilla#136] opened 2021-11-26 09:52 UTC
Hello, my client runs a restaurant and he uses TB with FiltaQuilla on his computer. Whenever an email with a specific subject arrives, it should be printed out automatically. This worked like a charme for quite a while now, but now it doesn't print anymore. I recreated this issue on two different systems, both won't print. Other filters like "mark as read" are still working, it's just the printing one.

**Comment by RealRaven2000** [comment] 2021-11-26 15:32
Duplicate of issue #130 - we are working on it - see detailed comments there. If you leave a comment or like there you will be notified on news about this bug.

**Closed as completed by RealRaven2000** 2021-11-26 15:32 UTC
