### ISSUE TITLE
Feature: allow email date and subject as name of saved attachment file

### ISSUE THREAD

**Issue by supersexy** [RealRaven2000/FiltaQuilla#162] opened 2022-05-19 15:57 UTC
I try to export many attachments and learned today that Thunderbird can not do that natively (horrible!) - fortunately your addon offers a very nice solution for that (wonderful!). *But* of course I need one more thing: I really would like to have the attachment files saved with 

email-date_email-subject_name-of-attachment.sfx (suffix according to original attachment suffix).

Somehow I got the idea that this might work with the JavaScript action filter, but I am not able to get the details for the attachment and do not know enough about the internals to understand if this is possible at all, so I am asking here. 

Can this be done? Would you like to add this as a feature?

THANKS!

**Comment by RealRaven2000** [comment] 2024-02-21 12:16
marking as duplicate of #197 - please follow there for updates!

**Closed as completed by RealRaven2000** 2024-02-21 12:16 UTC
Labels: attachments
