### ISSUE TITLE
Detach Attachments forgets filename.ext with several attachments from one e-mail

### ISSUE THREAD

**Issue by ojde** [RealRaven2000/FiltaQuilla#3] opened 2019-01-14 10:26 UTC
Version 1.4.1; 2018-12-03

I regularily find attachments named "configured-folder-1",  "configured-folder-2" in the parent directory of the configured folder.

Example: An e-mail has four attachments, FileA.pdf, FileB.pdf, FileC.pdf, and FileD.pdf. The detach-to folder is configured "d:\\_download\EmailAttach"

After running the filter (manual, triggered, no matter) I find the four files as follows:
d:\\_download\EmailAttach\FileA.pdf
d:\\_download\EmailAttach\FileB.pdf
**d:\\_download\EmailAttach-1**
**d:\\_download\EmailAttach-2**

The log says:
> [14.01.2019, 11:03:19] Filter "Manuell -- Anhänge nach d:\\_download\EmailAttach" auf die Nachricht Name <name@domain.tld> - message subject date time, angewendet Anhänge abtrennen nach

This seems only to happen, when there are **more than one** attachment attached to an e-mail. But I am not sure how many must be attached for this to happen. The last instance when I had this it were four. E-mails with less than that were detached correctly.

**Comment by RealRaven2000** [comment] 2019-01-14 11:51
quick question - shouldn't the correct path read d:\_download\EmailAttach\ ?

**Comment by RealRaven2000** [comment] 2019-01-14 12:47
hmm, looks like github swallows  the first backslash afteer the colon. I meant this:

D: \ _download \ ...

I think the very FIRST backslash missing (after the colon) is maybe github's fault.

**Comment by ojde** [comment] 2019-01-14 12:55
Ah, sorry. Example of reading what one thinks, not what actually is written. I have corrected my first post.

**Comment by rskhiri** [comment] 2019-02-13 12:35
hello,
I have the same issue with detached files named <folder-name>-1, <folder-name>-2... without extension, saved  in the parent of the directory I choose (<folder-name>)
It would be nice that detached file date/time are those of the email

**Comment by rskhiri** [comment] 2019-02-13 12:37
files names are attach-1, attach-2 if the folder is attach

**Comment by RealRaven2000** [comment] 2024-02-21 12:52
Let's close as duplicate of #197 and deal with any naming problems over there

**Closed by RealRaven2000** 2024-02-21 12:52 UTC
Labels: attachments
