### ISSUE TITLE
attachments are saved with zero size

### ISSUE THREAD

**Issue by tern222** [RealRaven2000/FiltaQuilla#4] opened 2019-01-14 10:33 UTC
when I create a filter with the action "SaveAttachmentTo" attachments are saved with size zero ((((((

**Comment by RealRaven2000** [comment] 2019-01-14 11:50
it's an IMAP account. The first thing you should cheek if Synchronisation & storage" is set to download all messages:
https://i.imgur.com/SbPr0LB.png

1) can you check the Javascript error log when you execute the filter manually?
2) make sure the attachments (in the bottom pane of video preview)  show a size different from 0kb

**Comment by legolegs** [comment] 2019-02-10 07:42
I find a workaround (for pop3 mailbox):
set your filter to be applied AFTER spamfilter.

**Comment by RealRaven2000** [comment] 2019-02-10 17:54
Cool - good idea. I guess junk filters only run after the whole message is streamed into the inbox (?)

**Comment by Alsirion** [comment] 2019-05-23 20:33
Hello I have same problem

![Безымянный](https://user-images.githubusercontent.com/1808659/58284375-21ba8280-7db3-11e9-975d-bfc358fd9ad3.png)

**Comment by RealRaven2000** [comment] 2019-05-24 08:27
> Hello I have same problem
> 
> ![Безымянный](https://user-images.githubusercontent.com/1808659/58284375-21ba8280-7db3-11e9-975d-bfc358fd9ad3.png)

I cannot reproduce this, but did you try @legolegs workaround (set to run after Junk filter)?

**Comment by marcusulpius** [comment] 2019-10-14 23:01
I am getting zero file attachment trying to auto download .csv attachments. Get a zero byte file saved to the location specified.

Office 365 email account.
0 bytes if ran after or before spam filter.
Account is already set to sync all.
Thunderbird v: 52.9.1
FiltaQuilla: 1.5

**Comment by eyalroz** [comment] 2020-01-06 19:41
The extension should probably warn or report an error if the saved attachment ends up being empty (irrespectively of whether that's due to a bug or not).

**Comment by RealRaven2000** [comment] 2020-01-21 13:40
Right. I wonder if we could add a delay for any attachment functions and whether they would run better after waiting for 5 seconds. I believe the filter actions do not have to run synchronously, so these actions can be queued for a little later (and hopefully Thunderbird will have more success saving the attachments)

**Comment by RealRaven2000** [comment] 2021-03-09 12:54
Just weeding out all attachment bugs, I am marking this one as duplicate of #55 and closing. Let's continue discussion over there.

**Closed by RealRaven2000** 2021-03-09 12:54 UTC
