### ISSUE TITLE
Save Attachments not Working (TB 102.1.0 64-bit)

### ISSUE THREAD

**Issue by SGKrueger** [RealRaven2000/FiltaQuilla#174] opened 2022-08-05 17:14 UTC
The save attachments option is not working properly.  I'm either getting multiple zero byte files with the attachment name and numerical add-on to name for additional copy or I'm not getting anything saved at all.

**Comment by RealRaven2000** [comment] 2022-10-02 14:11
could it be issue #177 or #176 ?

**Comment by RealRaven2000** [comment] 2022-12-06 11:03
Closing as duplicate of #195

**Closed as completed** 2022-12-06 11:03 UTC
