### ISSUE TITLE
Add sender to list shows no results

### ISSUE THREAD

**Issue by El-Pazzo** [RealRaven2000/FiltaQuilla#142] opened 2021-12-16 11:04 UTC
Hi,
The filter action add sender to list does not work anymore:
existing filters do not show that option when opening them but they show some other option and if you select Add sender to list, the dropdown is empty.

Br,
Pascal

**Comment by RealRaven2000** [comment] 2022-01-19 12:33
This was caused by Thunderbird converting their enums to Arrays - Here is a test version with quick fix:

[filtaquilla-3.3pre28.zip](https://github.com/RealRaven2000/FiltaQuilla/files/7897083/filtaquilla-3.3pre28.zip)

TO install, download the zip file and move into Thunderbird Add-ons Manager (without unpacking)

**Comment by El-Pazzo** [comment] 2022-01-20 12:43
Thanks, that looks good and seems to work. ;)

**Comment by RealRaven2000** [comment] 2022-01-20 16:20
Please, leave the closing of issue to me - I will close it when I release version 3.3 officially to avoid duplications.

**Comment by RealRaven2000** [comment] 2022-01-21 14:31
Fixed in 3.3, officially released today (21/02/22)

**Closed as completed by RealRaven2000** 2022-01-21 14:31 UTC
Labels: bug, Regression Tb91
